lib/tododohtml_web/router.ex
defmodule TododohtmlWeb.Router do
  use TododohtmlWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TododohtmlWeb.Plugs.CurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TododohtmlWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/users", UserController)
    resources("/sessions", SessionController, singleton: true, only: [:new, :create, :delete])
    resources("/boards", BoardController)

    resources "/tasks", TaskController do
      resources("/subtasks", SubtaskController, only: [:new, :create])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TododohtmlWeb do
  #   pipe_through :api
  # end
end

lib/tododohtml_web/views/layout_view.ex
defmodule TododohtmlWeb.LayoutView do
  use TododohtmlWeb, :view
end

lib/tododohtml_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tododo</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
  </head>

  <body id="MyPage">

    <header class="header">
      <nav class="navbar navbar-default">  
        <div class="container">  
          <div class="navbar-header">  
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavBar">  
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>    
            <a class="navbar-brand" href="<% page_path(@conn, :index) %>">tododo</a>
          </div>    
          <div class="collapse navbar-collapse" id="myNavBar">
            <ul class="nav navbar-nav navbar-right">
              <%= if @current_user do %>  
                <li><%= @current_user.email %></li>
                <li><%= link "log out", to: session_path(@conn, :delete), method: :delete %></li>
              <% else %>      
                <li><%= link "sign up", to: user_path(@conn, :new) %></li>
                <li><%= link "log in", to: session_path(@conn, :new) %></li>
              <% end %>  
            </ul>
          </div>  
        </div>
      </nav>
    </header>

    <div class="container-fluid">
      <%= if message=get_flash(@conn, :info) do %>
        <p class="alert alert-info" role="alert"><%= message %></p>
      <% end %>

      <%= if message=get_flash(@conn, :error) do %>
        <p class="alert alert-danger" role="alert"><%= message %></p>
      <% end %>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <footer class="container-fluid text-center">
      <a href="#myPage" title="To Top">
        <span class="glyphicon glyphicon-chevron-up"></span>
      </a>
      <p>Tododo is bring to you by mem</p>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>