lib/tododohtml_web/router.ex
defmodule TododohtmlWeb.Router do
  use TododohtmlWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(TododohtmlWeb.Plugs.CurrentUser)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", TododohtmlWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    resources("/users", UserController)
    resources("/sessions", SessionController, singleton: true, only: [:new, :create, :delete])
    resources("/boards", BoardController)

    resources "/tasks", TaskController do
      resources("/subtasks", SubtaskController, only: [:new, :create])
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TododohtmlWeb do
  #   pipe_through :api
  # end
end

lib/tododohtml/boards/board.ex
defmodule Tododohtml.Boards.Board do
  use Ecto.Schema
  import Ecto.Changeset

  schema "boards" do
    belongs_to(:user, Tododohtml.Accounts.User)
    has_many(:tasks, Tododohtml.Boards.Task)
    field(:title, :string)

    timestamps()
  end

  @doc false
  def changeset(board, attrs) do
    board
    |> cast(attrs, [:user_id, :title])
    |> validate_required([:title])
  end
end

lib/tododohtml/boards/boards.ex
defmodule Tododohtml.Boards do
  @moduledoc """
  The Boards context.
  """

  import Ecto.Query, warn: false
  alias Tododohtml.Repo

  alias Tododohtml.Boards.Board
  alias Tododohtml.Accounts.User

  @doc """
  Returns the list of boards.

  ## Examples

      iex> list_boards()
      [%Board{}, ...]

  """
  def list_boards do
    Repo.all(Board)
  end

  @doc """
  Gets a single board.

  Raises `Ecto.NoResultsError` if the Board does not exist.

  ## Examples

      iex> get_board!(123)
      %Board{}

      iex> get_board!(456)
      ** (Ecto.NoResultsError)

  """
  def get_board!(id) do
    Board
    |> Repo.get!(id)
    |> Repo.preload(tasks: :tasks)
  end

  def get_board!(%User{id: user_id}, title) do
    Board
    |> where(user_id: ^user_id)
    |> where(title: ^title)
    |> Repo.one!()
    |> Repo.preload(tasks: :tasks)
  end

  def get_user_board!(%User{id: user_id}, id) do
    Board
    |> where(user_id: ^user_id)
    |> where(id: ^id)
    |> Repo.one!()
    |> Repo.preload(tasks: :tasks)
  end


  @doc """
  Creates a board.

  ## Examples

      iex> create_board(%{field: value})
      {:ok, %Board{}}

      iex> create_board(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_board(attrs \\ %{}) do
    %Board{}
    |> Board.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a board.

  ## Examples

      iex> update_board(board, %{field: new_value})
      {:ok, %Board{}}

      iex> update_board(board, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_board(%Board{} = board, attrs) do
    board
    |> Board.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a Board.

  ## Examples

      iex> delete_board(board)
      {:ok, %Board{}}

      iex> delete_board(board)
      {:error, %Ecto.Changeset{}}

  """
  def delete_board(%Board{} = board) do
    Repo.delete(board)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking board changes.

  ## Examples

      iex> change_board(board)
      %Ecto.Changeset{source: %Board{}}

  """
  def change_board(%Board{} = board) do
    Board.changeset(board, %{})
  end

  alias Tododohtml.Boards.Task

  @doc """
  Returns the list of tasks.

  ## Examples

      iex> list_tasks()
      [%Task{}, ...]

  """
  def list_tasks do
    Repo.all(Task)
  end

  @doc """
  Gets a single task.

  Raises `Ecto.NoResultsError` if the Task does not exist.

  ## Examples

      iex> get_task!(123)
      %Task{}

      iex> get_task!(456)
      ** (Ecto.NoResultsError)

  """
  def get_task!(id), do: Repo.get!(Task, id)

  @doc """
  Creates a task.

  ## Examples

      iex> create_task(%{field: value})
      {:ok, %Task{}}

      iex> create_task(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_task(attrs \\ %{}) do
    %Task{}
    |> Task.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a task.

  ## Examples

      iex> update_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> update_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_task(%Task{} = task, attrs) do
    task
    |> Task.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Add a subtask to a task (A task to an outcome).

  ## Examples

      iex> add_task(task, %{field: new_value})
      {:ok, %Task{}}

      iex> add_task(task, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def add_task(%Task{} = parent, attrs) do
    result =
      %Task{parent_id: parent.id}
      |> Task.changeset(attrs)
      |> Repo.insert()

    case result do
      {:ok, _task} -> {:ok, Repo.get!(Task, parent.id) |> Repo.preload(:tasks)}
      {:error, _} -> result
    end
  end

  @doc """
  Deletes a Task.

  ## Examples

      iex> delete_task(task)
      {:ok, %Task{}}

      iex> delete_task(task)
      {:error, %Ecto.Changeset{}}

  """
  def delete_task(%Task{} = task) do
    Repo.delete(task)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking task changes.

  ## Examples

      iex> change_task(task)
      %Ecto.Changeset{source: %Task{}}

  """
  def change_task(%Task{} = task) do
    Task.changeset(task, %{})
  end
end

lib/tododohtml/boards/task.ex
defmodule Tododohtml.Boards.Task do
  use Ecto.Schema
  import Ecto.Changeset

  schema "tasks" do
    belongs_to(:board, Tododohtml.Boards.Board)
    belongs_to(:parent, Tododohtml.Boards.Task)
    has_many(:tasks, Tododohtml.Boards.Task, foreign_key: :parent_id)
    field(:description, :string)
    field(:status, :string)

    timestamps()
  end

  @doc false
  def changeset(task, attrs) do
    task
    |> cast(attrs, [:board_id, :description, :status])
    |> validate_required([:description, :status])
  end
end

lib/tododohtml_web/controllers/board_controller.ex
defmodule TododohtmlWeb.BoardController do
  use TododohtmlWeb, :controller

  alias Tododohtml.Boards
  alias Tododohtml.Boards.Board
  alias TododohtmlWeb.Plugs.CurrentUser


  plug :ensure_current_user

  def index(conn, _params) do
    boards = Boards.list_boards()
    render(conn, "index.html", boards: boards)
  end

  def new(conn, _params) do
    changeset = Boards.change_board(%Board{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"board" => board_params}) do
    case Boards.create_board(board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board created successfully.")
        |> redirect(to: board_path(conn, :show, board))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = CurrentUser.get(conn)
    board = Boards.get_user_board!(user, id)
    render(conn, "show.html", board: board)
  end

  def edit(conn, %{"id" => id}) do
    board = Boards.get_board!(id)
    changeset = Boards.change_board(board)
    render(conn, "edit.html", board: board, changeset: changeset)
  end

  def update(conn, %{"id" => id, "board" => board_params}) do
    board = Boards.get_board!(id)

    case Boards.update_board(board, board_params) do
      {:ok, board} ->
        conn
        |> put_flash(:info, "Board updated successfully.")
        |> redirect(to: board_path(conn, :show, board))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", board: board, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    board = Boards.get_board!(id)
    {:ok, _board} = Boards.delete_board(board)

    conn
    |> put_flash(:info, "Board deleted successfully.")
    |> redirect(to: board_path(conn, :index))
  end

  defp ensure_current_user(conn, _opts) do
    if CurrentUser.get(conn) do
      conn
    else
      conn
      |> put_flash(:error, "Log in or Sign up before you continue")
      |> redirect(to: page_path(conn, :index))
    end
  end
end

lib/tododohtml_web/views/board_view.ex
defmodule TododohtmlWeb.BoardView do
  use TododohtmlWeb, :view
end

lib/tododohtml_web/templates/board/edit.html.eex
<h2>Edit Board</h2>

<%= render "form.html", Map.put(assigns, :action, board_path(@conn, :update, @board)) %>

<span><%= link "Back", to: board_path(@conn, :index) %></span>

lib/tododohtml_web/templates/board/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/tododohtml_web/templates/board/index.html.eex
<h2>Listing Boards</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for board <- @boards do %>
    <tr>
      <td><%= board.title %></td>

      <td class="text-right">
        <span><%= link "Show", to: board_path(@conn, :show, board), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Edit", to: board_path(@conn, :edit, board), class: "btn btn-default btn-xs" %></span>
        <span><%= link "Delete", to: board_path(@conn, :delete, board), method: :delete, data: [confirm: "Are you sure?"], class: "btn btn-danger btn-xs" %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Board", to: board_path(@conn, :new) %></span>

lib/tododohtml_web/templates/board/new.html.eex
<h2>New Board</h2>

<%= render "form.html", Map.put(assigns, :action, board_path(@conn, :create)) %>

<span><%= link "Back", to: board_path(@conn, :index) %></span>

lib/tododohtml_web/templates/board/show.html.eex
<h2>Tododo Board</h2>

<div class="row">
  <div id="col-todo" class="col-sm-4 pannel">
    <h3>To do</h3>
    <button class="btn btn-default btn-sm" onclick='show_form("new-outcome")'>
      <span class="glyphicon glyphicon-plus"></span> outcome 
    </button>
    <div id="new-outcome" style="display:none;">
      <%= form_for @conn, task_path(@conn, :create) , fn f -> %>
        <div class="form-group">
          <%= label f, :description, class: "control-label" %>
          <%= text_input f, :description, class: "form-control" %>
          <%= error_tag f, :description %>
        </div>

        <div class="form-group">
          <%= submit "Submit", class: "btn btn-primary" %>
        </div>
      <% end %>
    </div>

    <div id="todo" class="task-list"  ondrop="drop(event, this)" ondragover="allowDrop(event)">
      <%= for task <- @board.tasks do %>
        <div id="<%= task.id %>" class="outcome">
          <%= task.description %>
        
          <button class="btn btn-default btn-sm" onclick='show_form("new-task-<%= task.id %>")'>
            <span class="glyphicon glyphicon-plus"></span> task 
          </button>
          <div id="new-task-<%= task.id %>" style="display:none;">
            <%= form_for @conn, task_subtask_path(@conn, :create, task), [method: "post"], fn f -> %>
              <div class="form-group">
                <%= label f, :description, class: "control-label" %>
                <%= text_input f, :description, class: "form-control" %>
                <%= error_tag f, :description %>
              </div>

              <div class="form-group">
                <%= submit "Submit", class: "btn btn-primary" %>
              </div>
            <% end %>
          </div>


          <%= for subtask <- task.tasks do %>
            <div id="<%= subtask.id %>" class="task <%= subtask.status %>" draggable="true" ondragstart="drag(event)">
              <%= subtask.description %>
            </div>
          <% end %>
        
        </div>
      <% end %>
    </div>
  </div>
  
  <div id="col-doing" class="col-sm-4 pannel">
    <h3>Doing</h3>
    <div id="doing" class="task-list" ondrop="drop(event, this)" ondragover="allowDrop(event)">
    </div>
  </div>
  
  <div id="col-done" class="col-sm-4 pannel">
    <h3>Done</h3>
    <div id="done" class="task-list" ondrop="drop(event, this)" ondragover="allowDrop(event)">
    </div>
  </div>
</div>

<script type="text/javascript">
  window.csrf_token = <%= raw Poison.encode!(Plug.CSRFProtection.get_csrf_token()) %>;
  body_elements = document.getElementsByTagName("body");
  body_elements[0].onload = function() {
    board = require("js/app").Board
    board.sort_task_list(["doing", "done"]);
    window.show_form = require("js/app").show_form
    window.drag = require("js/app").drag
    window.drop = require("js/app").drop
    window.allowDrop = require("js/app").allowDrop
  };
</script>